export const PUSH_GOMOKU = 'PUSH_GOMOKU'
export const GOMOKU_RESTORE = 'GOMOKU_RESTORE'

export const CHANGE_GOMOKU_INDEX = 'CHANGE_GOMOKU_INDEX'

export const CHANGE_IS_CURRENT = 'CHANGE_IS_CURRENT'
export const CHANGE_WIN = 'CHANGE_WIN'